name: Github cloud run test

on:
  schedule:
    - cron: '0 9 * * 1'
  workflow_dispatch:
    inputs:
      test_plan_type:
        description: "Select the test plan"
        required: true
        type: choice
        options:
          - Smoke
          - Regression
        default: Regression

env:
  PROJECT: 'Niffler/Niffler.xcodeproj'
  SCHEME: 'E2EUITests'
  DERIVED_DATA_PATH: 'DerivedData'
  TEST_RESULTS: './TestResults.xcresult'
  ALLURE_RESULTS: 'allure-results'
  SIMULATOR_VERSION: '18.2'
  SIMULATOR_NAME: 'iPhone 16'

jobs:
  test:
    name: test
    runs-on: [macos-15]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Allure Parser of XCResults
        run: |
          curl -OL https://github.com/eroshenkoam/xcresults/releases/download/1.19.0/xcresults
          chmod +x xcresults

      - name: Install Allure
        run: brew install allure

      - name: Run Ui Tests
        id: test
        run: |
          set -o pipefail
          xcodebuild test \
          -project ${{ env.PROJECT }} \
          -scheme ${{ env.SCHEME }} \
          -derivedDataPath ${{ env.DERIVED_DATA_PATH }} \
          -destination 'platform=iOS Simulator,name=${{ env.SIMULATOR_NAME }},OS=${{ env.SIMULATOR_VERSION }}' \
          -resultBundlePath ./TestResults.xcresult \
          CODE_SIGNING_ALLOWED='NO' \
          | xcbeautify --renderer github-actions
        continue-on-error: true

      - name: Generate Allure files
        run: |
          mkdir ${{ env.ALLURE_RESULTS }}
          ./xcresults export TestResults.xcresult -o ${{ env.ALLURE_RESULTS }}
          mkdir allure-report
          allure generate ${{ env.ALLURE_RESULTS }} --report-dir allure-report

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: |
            allure-results/
          retention-days: 1
          
      - name: Upload XCResult
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: ./TestResults.xcresult
          retention-days: 1
          
  report:
    runs-on: [ubuntu-latest]
    name: Report to Allure
    needs: test
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: ./allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
          
  notification:
    runs-on: macos-15
    needs: test
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: TestResults
          path: ./TestResults.xcresult

      - name: Parse and send results to Telegram
        run: |
          xcrun xcresulttool get --path ./TestResults.xcresult --format json --legacy > result.json
          total=$(jq -r '.metrics.testsCount._value' result.json)
          failed=$(jq -r '.metrics.testsFailedCount._value' result.json)
          passed=$((total - failed - skipped))

          TEXT="*🧪 Результаты тестов:*
          ✅ Успешных: $passed
          ❌ Упавших: $failed
          📊 Всего: $total"
          
          echo "$TEXT"

          curl -s -X POST https://api.telegram.org/bot7984906836:AAF2qXhlV5Qz9R31hBMhcqakBLAlpd01Eqg/sendMessage -d chat_id=273824728 -d text="$TEXT"