name: runTest

on: 
  workflow_dispatch:
    inputs:
      run_tests:
        description: "Запускать тесты?"
        required: true
        default: "true"
        type: boolean

env:
  PROJECT: 'Niffler/Niffler.xcodeproj'
  SCHEME: 'E2EUITests'
  DERIVED_DATA_PATH: 'DerivedData'
  TEST_RESULTS: './TestResults.xcresult'
  ALLURE_RESULTS: 'allure-results'
  SIMULATOR_VERSION: '18.3.1'
  SIMULATOR_NAME: 'iPhone 16'


jobs:
  build:
    name: Run test
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run test
        run: |
          set -o pipefail
          xcodebuild test \
          -project ${{ env.PROJECT }} \
          -scheme ${{ env.SCHEME }} \
          -destination 'platform=iOS Simulator,name=${{ env.SIMULATOR_NAME }},OS=${{ env.SIMULATOR_VERSION }}' \
          CODE_SIGNING_ALLOWED='NO' \
          | xcbeautify --renderer github-actions
